title: Open Femtosat
description: The Open Source Femtosatellite Project
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://femtosat.marvinlin.space

aux_links:
  Source Repository: https://github.com/marvinlinn/open-femtosatellite

# Add definitions for callouts and highlights
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Include Last Edit Timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html