title: Open Femtosatellite
description: The Open Source Femtosatellite Project
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

url: https://femtosat.marvinlin.space

aux_links:
  Source Repository: https://github.com/marvinlinn/open-femtosatellite
