title: Open Femtosatellite
description: The Open Source Femtosatellite Project
remote_theme: pmarsceill/just-the-docs

url: https://femtosat.marvinlin.space

aux_links:
  Template Repository: https://github.com/marvinlinn/open-femtosatellite
