name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  jekyll-build:
    name: Build (jekyll gem)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: false
    - name: Bundle Install (Jekyll ${{ matrix.jekyll-version }})
      run: bundle install
      env:
        BUNDLE_GEMFILE: fixtures/Gemfile-jekyll-${{ matrix.jekyll-version }}
    - name: Init Search
      working-directory: ./docs
      run: bundle exec rake search:init
      env:
        BUNDLE_GEMFILE: fixtures/Gemfile-jekyll-${{ matrix.jekyll-version }}
    - name: Build Site
      working-directory: ./docs
      run: bundle exec jekyll build
      env:
        BUNDLE_GEMFILE: fixtures/Gemfile-jekyll-${{ matrix.jekyll-version }}

        
